apiVersion: apps/v1
kind: Deployment
metadata:
  name: hlf-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlf-adapter
  template:
    metadata:
      labels:
        app: hlf-adapter
    spec:
      containers:
        - name: app
          image: public.ecr.aws/n4q1q0z2/hf:hf-adapter.0.24
          imagePullPolicy: Always
          resources:
            requests:
              memory: "50Mi"
              cpu: "0.1"

