

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epi-pvc-external-volume
spec:
  storageClassName: "gp2-ae"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


