apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: epipoc.demo
  name: epipoc
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: epipoc.demo
  type: NodePort
