apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: walletstore
  name: walletstore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
