---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-rms
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /var/hyperledger/rms.pharma.com
