---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-rms
spec:
  volumeName: fabric-rms
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
