
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-letsencrypt
spec:
  storageClassName: "gp2-ae"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
